---
variants:
  scope: variants
  parameters:
    referenceName:
      paramkey: 'variants.reference_name'
      dbkey: reference_name
      alias:
        - reference_name
      pattern: '^\w+?$'
    mateName:
      paramkey: 'variants.mate_name'
      dbkey: mate_name
      alias:
        - mate_name
      pattern: '^\w+?$'
    referenceBases:
      paramkey: 'variants.reference_bases'
      dbkey: reference_bases
      alias:
        - reference_bases
      pattern: '^[\w\*]+?$'
    alternateBases:
      paramkey: 'variants.alternate_bases'
      dbkey: alternate_bases
      alias:
        - alternate_bases
      pattern: '^\w+?$'
    variantType:
      paramkey: 'variants.variant_type'
      dbkey: variant_type
      alias:
        - variant_type
      pattern: '^\w+?$'
    start:
      paramkey: 'variants.start'
      dbkey: start
      alias:
        - start
      pattern: '^\d+?$'
      type: integer
    end:
      paramkey: 'variants.end'
      dbkey: end
      alias:
        - end
      pattern: '^\d+?$'
      type: integer
    startMin:
      paramkey: 'variants.start_min'
      dbkey: start_min
      alias:
        - start_min
      pattern: '^\d+?$'
      type: integer
    startMax:
      paramkey: 'variants.start_max'
      dbkey: start_max
      alias:
        - start_max
      pattern: '^\d+?$'
      type: integer
    endMin:
      paramkey: 'variants.end_min'
      dbkey: end_min
      alias:
        - end_min
      pattern: '^\d+?$'
      type: integer
    endMax:
      paramkey: 'variants.end_max'
      dbkey: end_max
      alias:
        - end_max
      pattern: '^\d+?$'
      type: integer

biosamples:
  scope: biosamples
  parameters:
    biocharacteristics.type.id:
      paramkey: 'biosamples.biocharacteristics.type.id'
      dbkey: 'biocharacteristics.type.id'
      alias:
        - 'biosamples-biocharacteristics-type-id'
        - 'biocharacteristics.type.id'
        - 'biocharacteristics-type-id'
      pattern: '^(\w+[\:$])?\w*?\d(?:[\w\-\.]+?)?'
      type: array
    external_references.type.id:
      paramkey: 'biosamples.external_references.type.id'
      alias:
        - 'biosamples-external_references-type-id'
        - 'external_references.type.id'
        - 'external_references-type-id'
      pattern: '^(\w+[\:$])?\w*?\d(?:[\w\-\.]+?)?'
      type: array

biosubsets:
  scope: biosubsets
  parameters:
    id:
      paramkey: 'biocharacteristics.type.id'
      dbkey: 'id'
      alias:
        - 'biosubsets-biocharacteristics-type-id'
        - 'biosubsets.biocharacteristics.type.id'
        - 'biocharacteristics.type.id'
        - 'biocharacteristics-type-id'
      pattern: '^\w+[\:$]?(?:[\w\-\.]+?)?'
      type: array

datacollections:
  scope: datacollections
  parameters:
    id:
      paramkey: 'external_references.type.id'
      dbkey: 'id'
      alias:
        - 'datacollections-external_references-type-id'
        - 'datacollections.external_references.type.id'
        - 'external_references.type.id'
        - 'external_references-type-id'
      pattern: '^\w+[\:$]?(?:[\w\-\.]+?)?'
      type: array

filters:
  scope: filters
  parameters:
    randno:
      paramkey: 'filters.randno'
      dbkey: 'randno'               # not really used this way
      alias:
        - randno
      pattern: '^\d+?$'
      type: integer
